### ISSUE TITLE
Dockerfile + Pixi Lock file for Gym

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_gym#152]
I know one of the most difficult things about getting started with gym is getting it installed. The last 2 weeks I've been working on creating a pixi environment and a docker file that could run gym with GPU access

To full integrate this change. We would need to modify the script to not require Tkinter since its incompatible with Docker and I did have some issues with the environment variables (that I ended up commenting out) in the train script. The version of the script I have attached is not ready for production but it should give you an idea how I got it to run.

[docker_setup.zip](https://github.com/user-attachments/files/19079994/docker_setup.zip)

## How to Edit the compose.yml
Currently the compose file is configured to connect to my folders in WSL to the docker container and you need to modify them to connect to folders on your computer. To modify this for your setup I'd change these lines ` /home/sharon/gym/segmentation_gym/my_segmentation_gym_datasets`, `/home/sharon/gym/segmentation_gym/my_segmentation_gym_datasets_v5`, and `/home/sharon/gym/segmentation_gym/model_from_scratch_test_v5`. If you don't want to have access to any of these directories in your docker container then just remove them from the compose file
```
version: "3.8"
services:
  pixi-cuda:
    build:
      context: .
      dockerfile: dockerfile
    image: pixi-cuda  # Important: Use the same image name as in your docker build command
    runtime: nvidia
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - type: bind
        source: /home/sharon/gym/segmentation_gym/my_segmentation_gym_datasets # change this to your folder
        target: /gym/my_segmentation_gym_datasets
      - type: bind
        source: /home/sharon/gym/segmentation_gym/my_segmentation_gym_datasets_v5 # change this to your folder
        target: /gym/my_segmentation_gym_datasets_v5
      - type: bind
        source: /home/sharon/gym/segmentation_gym/model_from_scratch_test_v5 # change this to your folder
        target: /gym/model_from_scratch_test_v5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
## How to build the docker container
1. Install docker desktop
2. Either in WSL or Windows Powershell run `docker` to make sure docker is running
3. Build and Run the docker environment
`docker compose up --build -d`
- This builds the docker container and the `-d` flag means run in `d`etached mode so that it won't attach to your terminal 
4. Figure out the ID of your docker container
`docker ps`
- In the example below my docker container has the ID `d7162011b821 `
```
(base) sharon@Sharonator:~$ docker ps
CONTAINER ID   IMAGE       COMMAND                  CREATED          STATUS          PORTS     NAMES
d7162011b821   pixi-cuda   "/gym/entrypoint.sh …"   58 minutes ago   Up 58 minutes             segmentation_gym-pixi-cuda-1
(base) sharon@Sharonator:~$ docker exec -it d7162011b821 /bin/bash
```
5. Connect to the docker container
`docker exec -it <CONTAINER ID> /bin/bash`
- Below you can see that I connect to the docker container and run `ls` in it and I can see the gym environment I copied to it. You can also the folders I mounted `model_from_scratch_test_v5`  `my_segmentation_gym_datasets_v5` and `my_segmentation_gym_datasets`.

```
(base) sharon@Sharonator:~$ docker ps
CONTAINER ID   IMAGE       COMMAND                  CREATED          STATUS          PORTS     NAMES
d7162011b821   pixi-cuda   "/gym/entrypoint.sh …"   58 minutes ago   Up 58 minutes             segmentation_gym-pixi-cuda-1
(base) sharon@Sharonator:~$ docker exec -it d7162011b821 /bin/bash
root@d7162011b821:/gym# ls
entrypoint.sh               my_segmentation_gym_datasets     pixi.lock       resunet_report.txt       setup_cudnn.sh  test_gpus.py
model_from_scratch_test_v5  my_segmentation_gym_datasets_v5  pyproject.toml  seg_images_in_folder.py  src             train_model_script.py
root@d7162011b821:/gym# pixi shell
(segmentation_gym) root@d7162011b821:/gym#                                                                                                                                                                       
```
6. Run `pixi shell` to activate the pixi environment that has the gym environment install
`pixi shell`
- You should see `(segmentation_gym) ` appear in the output
```
root@d7162011b821:/gym# pixi shell
(segmentation_gym) root@d7162011b821:/gym#                                                                                                                                                                       
```
7. Now you can run any script you want.
- For this example I'll run the train model script which is currently configured to use the GPU on my host to train the model
```
python train_model_script.py --config_file /gym/my_segmentation_gym_datasets_v5/config/hatteras_l8_resunet.json --train_data_dir /gym/model_from_scratch_test_v5/train_data/train_npzs --val_data_dir /gym/model_from_scratch_test_v5/val_data/val_npzs
```
- Beginning of output of running this command
```
root@d7162011b821:/gym# pixi shell
(segmentation_gym) root@d7162011b821:/gym# python train_model_script.py --config_file /gym/my_segmentation_gym_datasets_v5/config/hatteras_l8_resunet.json --train_data_dir /gym/model_from_scratch_test_v5/train_data/train_npzs --val_data_dir /gym/model_from_scratch_test_v5/val_data/val_npzs
2025-03-05 01:22:07.882280: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-05 01:22:08.098311: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
train_data_dir = /gym/model_from_scratch_test_v5/train_data/train_npzs
val_data_dir = /gym/model_from_scratch_test_v5/val_data/val_npzs
config_file = /gym/my_segmentation_gym_datasets_v5/config/hatteras_l8_resunet.json
weights = /gym/my_segmentation_gym_datasets_v5/weights/hatteras_l8_resunet.h5
SET_GPU: 0
SET_PCI_BUS_ID: True
Using GPU
USE_GPU: True
Using single GPU device
Version:  2.12.1
Eager mode:  True
2025-03-05 01:22:11.301771: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-05 01:22:11.428461: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-05 01:22:11.428537: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
physical_devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
physical_devices after set visible devices : [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2025-03-05 01:22:11.428796: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
 After setting memory growth: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
tf.config.get_visible_devices() [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
USE_MULTI_GPU: False
physical_devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```
7. And when you're done running docker here's how you stop
- `exit` : this exits the terminal
- `docker stop <container id>`
```
root@d7162011b821:/gym# exit
exit
(base) sharon@Sharonator:~$ docker ps
CONTAINER ID   IMAGE       COMMAND                  CREATED             STATUS             PORTS     NAMES
d7162011b821   pixi-cuda   "/gym/entrypoint.sh …"   About an hour ago   Up About an hour             segmentation_gym-pixi-cuda-1
(base) sharon@Sharonator:~$ docker stop d7162011b821
d7162011b821
(base) sharon@Sharonator:~$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
